### ISSUE TITLE
strict mode: recovery vs unknown and how to distinguish between them

### ISSUE THREAD

**Issue by hartman** [CSSLint/parser-lib#112]
Per README:
strict - set to true to disable error recovery and stop on the first syntax error. Default is false.

I have concerns about the  "any @ rules that isn't recognized is automatically skipped, meaning the entire block after it is not parsed" part though. Does this really qualify as a syntax error ?

For instance, in my opinion, errors should fail csslint, but if you want to introduce new @rules that parser-lib doesn't know about, these would emit errors in strict mode, even though I have no intention of correcting them. Instead I would have to ignore all OTHER errors as well. Now we could of course say that csslint should handle each type of error individually, but there is no type flag, just individual messages, which are probably not really a good idea to use as identifiers in themselves.

Anyone got ideas to improve upon this ?

**Comment by frvge** [comment]
You can disable rules and ignore files or sections of code with CSSlint. This should give enough power to bypass issues like these. See https://github.com/CSSLint/csslint/wiki/Ignoring-parts-of-CSS-during-linting
