### ISSUE TITLE
Support for ReadableStream

### ISSUE THREAD

**Issue by oncletom** [CSSLint/parser-lib#126]
Hello,

by digging into the API I noticed you use your own implementation of streams.
Do you have any plan to support Node.js ReadableStream?

Actually StreamReader.js considers a string as a finite entity. By enabling a ReadableStream compatible StreamReader, it would not drastically change the parser API, I think.

Plus, it would enable CSSLint/csslint#230 to be solved.

What do you think?

**Comment by cscott** [comment]
Creating a "StringReader" which accepts `ReadableStream` should be fine.  The StringReader does support lookahead, so you'd need to implement a small buffer, but that's not terribly hard.
