### ISSUE TITLE
Hiding comment tokens impacts ability to do checkstyle-type parsing of CSS

### ISSUE THREAD

**Issue by jackwanders** [CSSLint/parser-lib#127]
Currently, `COMMENT` tokens are marked with `hide: true, channel: 'comment'` in [`Token.js`](https://github.com/CSSLint/parser-lib/blob/master/src/css/Tokens.js#L13). Both of these properties prevent CSS comment tokens from being added to the stream and therefore acted upon (i.e., firing an event).

Being able to know when CSS style comments (`/* ... */`) are encounted in the token stream seems like it would be valuable information when doing checkstyle-type validation of a stylesheet. In particular, I am writing a CSS checkstyle program, and one rule option is to enforce a line of whitespace between CSS rules. In the sample below, the comment would not count as whitespace:

```css
.foo {
  margin: 10px;
}
/* this should not count as whitespace */
.bar {
  padding: 20px;
}
```

Unfortunately, `parser-lib` does not provide any event when entering or leaving a comment, and therefore, there does not appear to be any way to know that the one line gap between one `endrule` event and the next `startrule` event is populated with a CSS comment.

I have forked `parser-lib` and committed a few small changes that would remove the `hide` and `channel` properties from the `COMMENT` token type, and adds a `_comment` token-type handler that adds two new events: `startcomment` and `endcomment`.

https://github.com/jackwanders/parser-lib/compare/dont-hide-css-comments

I suppose another possible solution would be to allow a parser to be initialized with an array of channels to listen on, so that adding comments to the token stream and event list would be an opt-in procedure.

Are there any thoughts on this proposal?

Thanks.

**Comment by cscott** [comment]
I believe this was fixed with PR #147.
