### ISSUE TITLE
Create next release (v0.2.6) using latest Master 

### ISSUE THREAD

**Issue by KaptenJansson** [CSSLint/parser-lib#135]
There are some changes in the latest Master that I would like to use, when are the plans to create the next release and push to npm?

**Comment by kkirsche** [comment]
I'm interested in knowing when the next release is scheduled as year. It's almost been a year with no new versions...

**Comment by vsa** [comment]
+1, right now I have to work around issues which were already resolved months ago.

**Comment by sbryan** [comment]
+1  @nschonni 

A new release will allow other dependant libs/modules (csslint and in turn grunt-contrib-csslint) update and remain relevant too.  Adding ignored files or test result exceptions is becoming a maintenance headache and masking real issues.

**Comment by Keyes** [comment]
+1, as we are already using "will-change" in one project, csslint prints warnings - with a new release this property is already supported

**Comment by ChaosExAnima** [comment]
+1, we need a new release in order to support `@document`.

**Comment by cscott** [comment]
@XhmikosR what's the process for this?  I'm wondering whether it makes sense to make a release before #205 is merged, just in case there are some folks who have dependencies on the old build process or file organization.

**Comment by XhmikosR** [comment]
No idea, I don't make the releases myself.

/CC @stubbornella

**Comment by sbryan** [comment]
+1 ... anxiously awaiting a new, "official" release!

**Comment by ideadapt** [comment]
+1

**Comment by frvge** [comment]
+1

**Comment by ideadapt** [comment]
@XhmikosR So who is making the releases? Whats the status here?

**Comment by frvge** [comment]
I'd like to do it, because I need a new version myself, but I'm not a Node developer. It makes more sense if a dev does it. I don't want to mess things up ^^

@XhmikosR , @nschonni , can we get an update? :)

**Comment by XhmikosR** [comment]
The reason this is stalled is because of https://github.com/CSSLint/parser-lib/commit/970f8ce4f48a4e178c34e25d79879a7fbed302eb#commitcomment-16856256

**Comment by frvge** [comment]
Ok.

**Comment by ideadapt** [comment]
@XhmikosR I've read that the changelog problem has no been "solved". I also see that csslint has some open issues, but that should not prevent parser-lib from releasing a new version. 

What needs to be done before we can release a new parser-lib version?

**Comment by XhmikosR** [comment]
@ideadapt: it sort of is solved in the beta branch since I just got rid of the script.

Please see https://github.com/CSSLint/csslint/issues/514#issuecomment-208955752

**Comment by ideadapt** [comment]
@XhmikosR I saw that :) I just don't see how csslint prevents parser-lib from releasing a new version. I mean, there will be no harm for csslint. Although, they need to migrate some things when they update their dependency to the new version.

**Comment by XhmikosR** [comment]
The thing is there have been many changes that I'm not sure how the projects that depend on parser-lib will behave.

That is why I made beta branches for both projects. We just need some people to test those and report back.

**Comment by ideadapt** [comment]
Except of https://github.com/CSSLint/parser-lib/issues/21, csslint#beta successfully validated my 30k lines of css with no false positives spotted. Both versions found the same set of issues.

**Comment by XhmikosR** [comment]
That is good to hear.

I could go ahead and publish v1.0.0 hoping we won't have any major issues.

But my concern is that @cscott seems to have lost interest so there aren't any other people active. We'll see how it goes.

**Comment by ideadapt** [comment]
> so there aren't any other people active
Since their advancements would not be released any how …

> I could go ahead and publish v1.0.0
I would really appreciate that :)

**Comment by XhmikosR** [comment]
https://github.com/CSSLint/parser-lib/releases/tag/v1.0.0
