### ISSUE TITLE
StackOverflowError when running `ant test`

### ISSUE THREAD

**Issue by jawshooah** [CSSLint/parser-lib#136]
Seems there's an infinite recursion somewhere in the test code. Here's a [gist](https://gist.github.com/jawshooah/8eac688c1808188eb29e) with the console output.

**Comment by ovanderzee** [comment]
I also have a problem with ant test, occurs when 
             <arg path="${lib.dir}/yuitest-rhino-cli.js" />
(line 93 of build.xml as of now) is reached.

Setup:
Mac OS X 10.10.5
Apache Ant(TM) version 1.9.6 compiled on June 29 2015

**Comment by ovanderzee** [comment]
I also have a problem with ant test, occurs when 
        &lt;arg path="${lib.dir}/yuitest-rhino-cli.js" /&gt;
(line 93 of build.xml as of now) is reached.

Setup:
Mac OS X 10.10.5
Apache Ant(TM) version 1.9.6 compiled on June 29 2015

**Comment by ovanderzee** [comment]
For me, the problem disappeared by reverting java from jdk1.8.0_51 to jdk1.7.0_67

**Comment by ideadapt** [comment]
+1 for a long term fix :)
thanks to @ovanderzee reverting to jdk 1.7 worked for me as well.

**Comment by cscott** [comment]
See #179 which includes 2c812dc58d3b3697160318e5ddd7668702077dd5 to address this issue.

**Comment by cscott** [comment]
I created a standalone pull request for this issue (#185).
