### ISSUE TITLE
Allow vertical-align: inherit; as browsers do use it

### ISSUE THREAD

**Issue by aripalo** [CSSLint/parser-lib#151]
If I understood right, `vertical-align` shouldn't take value of `inherit` if one is to believe [MDN](https://developer.mozilla.org/en/docs/Web/CSS/vertical-align), but then again browsers seem to implement it with `td` elements for example:

- http://trac.webkit.org/browser/trunk/Source/WebCore/css/html.css#L250
- http://mxr.mozilla.org/mozilla-central/source/layout/style/html.css

That is why I think `inherit` should be added to https://github.com/CSSLint/parser-lib/blob/master/src/css/Properties.js#L526:

```js
"vertical-align"                : "auto | use-script | baseline | sub | super | top | text-top | central | middle | bottom | text-bottom | <percentage> | <length>",
```

**Comment by mattiacci** [comment]
'inherit' is indeed a valid value of 'vertical-align':
http://www.w3.org/TR/CSS21/visudet.html#propdef-vertical-align.

**Comment by lorenz068** [comment]
I have the same problem, please add this value! Thanks...to release a new version too :+1:
