### ISSUE TITLE
#145 breaks line numbering in case of sequential CRs: `\n\n` is replaced with `\n`

### ISSUE THREAD

**Issue by tophf** [CSSLint/parser-lib#155]
before #145 | after #145
--------|----------
![before-fs8](https://cloud.githubusercontent.com/assets/1310400/7617385/6a599342-f9b3-11e4-9864-6b963892ee08.png) | ![after-fs8](https://cloud.githubusercontent.com/assets/1310400/7617394/6f0daa36-f9b3-11e4-9fee-c4e17b3c9edb.png)

This would work correctly: 

```js
replace(/\r\n/g, "\n").replace(/\r/g, "\n")
```

BTW since both replace() have simple expressions it's 2.5 times faster (Chrome) than currently used `(\r|\n){1,2}`, you can test it by executing `s=prompt(); console.time(1); for(i=0;i<1000;i++) ss=s.replace(/\r\n/g, "\n").replace(/\r/g, "\n"); console.timeEnd(1);` in the console (paste something big in the prompt window, for example [node-parserlib.js](https://github.com/CSSLint/parser-lib/raw/master/release/node-parserlib.js) contents. Then compare with the current code's regexp.

**Comment by cscott** [comment]
This is addressed by PR #192.
