### ISSUE TITLE
How to split multiple selectors with this lib? 

### ISSUE THREAD

**Issue by ghost** [CSSLint/parser-lib#167]
How to split multiple selectors with this lib?

**Comment by tophf** [comment]
See [an example](https://github.com/CSSLint/parser-lib#startrule-and-endrule-events) in the readme

**Comment by acterhd** [comment]
But for me need split string.

**Comment by tophf** [comment]
I don't understand why you can't use that example. Maybe someone else will be able to lucky-guess what you actually need :-)

**Comment by acterhd** [comment]
Can I gen from selector object selector string?

**Comment by tophf** [comment]
What is a "selector object"? There's no such term. I'd be more helpful if you edit your first post and add an example, code, something. And delete the other comments, they make no sense anyway.

**Comment by acterhd** [comment]
```
function parseSelector(selectors){
	var parser = new parserlib.css.Parser();
	parser.addListener("startrule", function(event){
		for (var i=0,len=event.selectors.length; i < len; i++){
			var selector = event.selectors[i];
                        //There is string or object? How to I get string of separate selector?
		});
	});
	parser.parse(selectors + " {}");
}
```

**Comment by tophf** [comment]
Now it makes sense, thanks. The example I've linked in the beginning shows how to access the `selector` object and use its various properties. You can also see what's inside by simply using the developer tools debugger (usually F12 key in the browser).

**Comment by acterhd** [comment]
Can you update release (folder) library?

**Comment by tophf** [comment]
>Can you update release (folder) library?

What do you mean?

Also an example, `a:link, section#top > div:hover:not(.something) {}`:

![screenshot](https://cloud.githubusercontent.com/assets/1310400/10304498/479e2ec0-6c23-11e5-9e51-b3131a369756.png)

As you can see there's a lot of info. You probably want `.text` property.

**Comment by acterhd** [comment]
I mean updated compiled version. I see last release dated year ago.

**Comment by tophf** [comment]
Well, I'm not the maintainer so I can't. 

For Stylish-chrome I was building it manually, with some of the pull requests that rot here unmerged for years(?).

**Comment by acterhd** [comment]
Okay. I added multiple selectors support. 
https://github.com/acterhd/query-pro
