### ISSUE TITLE
Allow for "appearance" value "radio"

### ISSUE THREAD

**Issue by dlockhart** [CSSLint/parser-lib#170]
The [official draft spec](https://drafts.csswg.org/css-ui-4/#appearance-switching) seems to be heading in the direction of only allowing `auto` and `none` as possible values for the `appearance` property. However, [at least Firefox](https://developer.mozilla.org/en-US/docs/Web/CSS/-moz-appearance) supports a value of `radio`, and [this article](https://css-tricks.com/almanac/properties/a/appearance/) implies that Webkit does as well.

**Comment by frvge** [comment]
See also #176 as follow-up/verification.
