### ISSUE TITLE
Add "auto" (and more values?) for "appearance" property

### ISSUE THREAD

**Issue by frvge** [CSSLint/parser-lib#176]
The current list of supported properties for "appearance" did not look exhaustive to me, compared to various documentation sources.

Look into the supported properties of the various browsers and compile the "full" list.

**Comment by cscott** [comment]
The spec for `appearance` is at https://drafts.csswg.org/css-ui-4/#appearance-switching and it says, "Note: This specification intentionally refrains from making the appearance of all possible form controls and sub-controls available as values, as had previously been attempted by earlier proposals for this property and by several UA vendors in experimental implementations. Experience has shown that such a list would be very long and not practical to maintain, and UAs would need to add non-standard values to account for the behavior of non-standard pseudo-elements sometimes used to implement form controls. Moreover, many values of such an enumeration only make sense on a single element or pseudo-element, and are never used outside of the UA stylesheet. Instead, this specification only provides auto, none. UAs cannot therefore use the appearance property in the UA stylesheet to give each control is native look and feel, and must use appearance:auto instead."

So the only spec-compliant values appear to be "none" and "auto", although a larger set of values is presumably permitted for the prefixed versions of the property.

**Comment by cscott** [comment]
Actually, we don't seem to support `auto` at all right now, which would be a bug.

**Comment by frvge** [comment]
@cscott That's known. We want to support everything that's in use for the "old" system, as well as the 2 real values according to the actual CSS UI4 spec.

**Comment by cscott** [comment]
It seems we should support all the existing values for the *prefixed* properties, but for unprefixed `appearance` only support `auto` and `none` as per spec.
