### ISSUE TITLE
Switch to Grunt/npm scripts instead of ant

### ISSUE THREAD

**Issue by XhmikosR** [CSSLint/parser-lib#191]
Also, clean up release folder, keep one dist dir.

**Comment by kkirsche** [comment]
Out of curiosity, is there a reason to go with Grunt instead of Gulp? Or is that just preference?

**Comment by XhmikosR** [comment]
Personally, I don't like using Gulp. Sure, it has its pros but I'm used to Grunt and I prefer it.

**Comment by cscott** [comment]
...or even no build tool at all, just `package.json`.  The single-file packaging could be done by `browserify` instead of being done by ad-hoc scripts in an ant or grunt file.

**Comment by XhmikosR** [comment]
Oh, plus that's what CSS Lint is using.

**Comment by XhmikosR** [comment]
@cscott: sure if we don't end up with 30 script lines of 80 characters each then npm scripts are good. Either way, the ant approach is just bad IMO.

**Comment by cscott** [comment]
(The only really interesting thing the antfile seems to be doing is updating the CHANGELOG, which could be done with a separate maintainer script in `bin/`.)

**Comment by XhmikosR** [comment]
Changelog is moot IMO too, because it's just git log without the merges.

**Comment by cscott** [comment]
Work in progress at https://github.com/cscott/parser-lib/tree/de-ant-ify

Current remaining work to be done: https://github.com/cscott/parser-lib/blob/de-ant-ify/TODO

**Comment by XhmikosR** [comment]
Personally I'm used to having a dist directory with the needed files minus
package.json.

**Comment by cscott** [comment]
I'm not sure exactly what you mean.  parser-lib currently has a `release` directory with built files -- although most people won't actually need to use them.  Are you saying you prefer `dist` as the name of that directory?

**Comment by stubbornella** [comment]
I'm excited you are doing this work. Js build tools ftw!

**Comment by XhmikosR** [comment]
@cscott: yeah. See the csslint repo for example.

**Comment by cscott** [comment]
@XhmikosR do you think we should do the bundling step directly into the (version-controlled) `dist` directory -- or maintain the fact that builds go into `build` (which is `.gitignore`d) and then have a separate `release` step to copy stuff from `build` to `dist`?

It looks like csslint just bundles directly into `dist`, but we might want to eventually run browser-based tests against `build` of the latest sources, not against the latest "released" sources.
