### ISSUE TITLE
Expected RBRACE errors

### ISSUE THREAD

**Issue by Terrycoco** [CSSLint/parser-lib#216]
I've seen these in quite a few posts.  Getting "Expected RBRACE" errors when CSS has some sort of function ( ) like so:

    .spin-out.mui-leave.mui-leave-active {
             -webkit-transform: rotate(0.75turn);   /* passes */
             -ms-transform: rotate(0.75turn);        /*fails*/
              transform: rotate(0.75turn);              /*fails*/
      opacity: 0; }

Its curious that the first line passes, only subsequent ones fail.  Is there a workaround for this?

**Comment by Terrycoco** [comment]
EDIT: The above snippet was taken from foundation.css, with the second 2 lines failing (amongst others).  However, if I isolate the code above and test alone, all three lines fail. I attached listeners and here's what  I got:

    Property '-webkit-transform' has a value of 'rotate(null)' and isn't important. (2,10)
    Parse error: Expected RBRACE at line 2, col 36. (2,36) error
    Property '-ms-transform' has a value of 'rotate(null)' and isn't important. (3,10)
    Parse error: Expected RBRACE at line 3, col 32. (3,32) error
    Property 'transform' has a value of 'rotate(null)' and isn't important. (4,11)
    Parse error: Expected RBRACE at line 4, col 29. (4,29) error

It appears that the inner content of the parentheses are not being set?

**Comment by mattiacci** [comment]
Yep. I believe CSSLint doesn't yet support "turn" units.
