### ISSUE TITLE
Valid values for text-decoration need updating

### ISSUE THREAD

**Issue by gouch** [CSSLint/parser-lib#219]
`text-decoration` is now a shorthand property and so has several more valid values. csslint incorrectly flags these as errors.
- Valid CSS: `text-decoration: underline wavy red;`
- Incorrect csslint error: "Expected end of value but found 'wavy'. (known-properties)"

[See documentation](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration)

These new `text-decoration` values are used in the popular normalize.css library.

**Comment by ideadapt** [comment]
wavy and others are [css 3 draft state](https://drafts.csswg.org/css-text-decor-3/#propdef-text-decoration), which is not covered by parser-lib.

**Comment by gouch** [comment]
I'm not sure why you think CSSLint ignores draft rules. I see [lots of rules](https://github.com/CSSLint/parser-lib/blob/master/src/css/Properties.js) in both working draft and candidate recommendation status (e.g. `column-rule`).

The new `text-decoration` values are used in [normalize.css](https://github.com/necolas/normalize.css/blob/5d728b83a5ee6ee3e9e3158a28d6369718014e0c/normalize.css#L127), which makes its way into a lot of other places (including this very issues page), which is why this error is particularly annoying.

**Comment by ideadapt** [comment]
I thought so, because I see some of https://github.com/CSSLint/parser-lib/labels/Not%20in%20latest%20official%20spec being in draft state. But your right, Properties.js has a lot of css3 draft things in it :(

Maybe a PR will be accepted. Would you mind to create one?
