### ISSUE TITLE
Add all SVG properties

### ISSUE THREAD

**Issue by skrat** [CSSLint/parser-lib#28]
See https://github.com/stubbornella/csslint/issues/283#issuecomment-6091142

**Comment by lukasoppermann** [comment]
+1 Yes, please add stroke and fill at least.

**Comment by janaspage** [comment]
Just want to add a "me, too". The linter is flagging the property `fill`, which is common in CSS when using SVG iconography. Thanks!

**Comment by cscott** [comment]
A bunch of these were fixed in PR #150, #177, #187, #190, #195.  Can someone audit the current code, figure out what's still missing, and file a more specific bug report?  Thanks.

**Comment by dotnetCarpenter** [comment]
@cscott I'm not sure where to look but after using `stroke-width` in a code pen, I got _Unknown property 'stroke-width'._  Assuming codepen.io is using the latest CSSLint, `stroke-width` is missing.
http://codepen.io/dotnetCarpenter/pen/mREvjL

**Comment by dotnetCarpenter** [comment]
scratch that. found it https://github.com/CSSLint/parser-lib/blob/master/src/css/Properties.js#L423

**Comment by wkeese** [comment]
I think you can close this, Properties.js now has fill, stroke, etc.

**Comment by frvge** [comment]
Closing for now. Please reopen if something important is missing.
