### ISSUE TITLE
Add @document and @-moz-document support

### ISSUE THREAD

**Issue by nschonni** [CSSLint/parser-lib#53]
Currently they get flagged as an unknown @ directive
https://developer.mozilla.org/en-US/docs/CSS/@-moz-document?redirect=no
https://developer.mozilla.org/en-US/docs/CSS/@document

**Comment by ctumolosus** [comment]
Is there a workaround for this problem? As mentioned in other comments this directive is useful for targeting firefox.

**Comment by IvanGuardado** [comment]
What I did was to move all this kind of stuff to a separate file `firefox.css` and exclude it from the lint process.

**Comment by jawshooah** [comment]
Any progress on this? I'd love to be able to lint my CSS without resorting to @IvanGuardado's workaround.
