### ISSUE TITLE
Add @supports to the list of known at-rules

### ISSUE THREAD

**Issue by aghassemi** [CSSLint/parser-lib#93]
`@supports` is now supported by Chrome and Firefox but gets flagged as unknown @ rule.

**Comment by delka** [comment]
+1

**Comment by SelenIT** [comment]
CSS Conditional Rules Level 3 spec, that introduces `@support` rule, is now part of [the Official Definition of the CSS](http://www.w3.org/TR/CSS/#css) (sic!). Shouldn't marking it as _error_ be now considered as a _bug_ of the linter?

**Comment by XhmikosR** [comment]
Fixed in #196.
